### ISSUE TITLE
多线程使用？

### ISSUE THREAD

**Issue by MrXue** [aliyun/aliyun-oss-cpp-sdk#14]
官方例子中并没有多线程下使用的最佳实践。请问多线程下是一个线程使用一个Client；还是多个线程可以使用同一个Client实例，不需要加锁？还是有其他更好的实现？

**Comment by huiguangjun** [comment]
client 本身提供了一些异步上传下载的接口，可以直接使用。
也可以创建自己的线程，通过同一个client 发起请求。
你不需要额外加锁。
