### ISSUE TITLE
ResumableDownloader下载导致崩溃

### ISSUE THREAD

**Issue by xflyWH** [aliyun/aliyun-oss-cpp-sdk#17]
当最后一个part快下载完成时退出系统调用disableRequest，最后一个part下载完成后返回ClientError:100002", "Disable all requests by upper. 下次进入系统后读取上次的下载记录， 因为所有的part都已经下载完成partsToDownload会是空，不会产生请求，     在执行auto meta = outcomes[0].result().Metadata();会崩溃

**Comment by huiguangjun** [comment]
谢谢反馈，这个问题会在 1.5.0 版本上修复。

在这个情况下，会先通过headobject 获取到 Metadata

**Comment by huiguangjun** [comment]
fix in dev-1907  branch
