### ISSUE TITLE
请问能不能提供一版带rtti的c++ OSS库，鸿蒙上用

### ISSUE THREAD

**Issue by Rouge0505** [aliyun/aliyun-oss-cpp-sdk#179]
我们的工程要求rtti，OSS的so不带rtti，派生CredentialsProvider会编译报错ld.lld: error: undefined symbol: typeinfo for AlibabaCloud::OSS::CredentialsProvider

**Comment by Rouge0505** [comment]
编译报错ld.lld: error: undefined symbol: typeinfo for AlibabaCloud::OSS::CredentialsProvider

**Comment by huiguangjun** [comment]
cmake 阶段，可以通过  DENABLE_RTTI 选项来设置 RTTI, 例如 
cmake .. -DENABLE_RTTI=OFF   或  cmake .. -DENABLE_RTTI=ON
