### ISSUE TITLE
关于设置Http代理时连接错误问题

### ISSUE THREAD

**Issue by mianchi68** [aliyun/aliyun-oss-cpp-sdk#21]
sdk 1.4.0版本 CurlHttpClient.cc(518行) 
ss << proxyScheme_ << "://" << proxyHost_;
proxyScheme_是一个枚举型，std::stringstream默认识别为整型，导致ss的结果是0://10.10.10.10
修正：
ss << OSS::Http::SchemeToString(proxyScheme_) << "://" << proxyHost_;
修改验证结果可行。

**Comment by huiguangjun** [comment]
fix in dev-1907 branch
