### ISSUE TITLE
mac链接失败

### ISSUE THREAD

**Issue by lsnbing** [aliyun/aliyun-oss-cpp-sdk#28]
mac下，生成dylib后，链接到程序提示链接不到符号，看了下符号表
<img width="480" alt="屏幕快照 2019-07-13 18 40 29" src="https://user-images.githubusercontent.com/6168604/61170611-4d314080-a59e-11e9-83ba-c770319a3bd0.png">

没办法，改了
```
#if !defined(ALIBABACLOUD_DECL_EXPORT)
#   define ALIBABACLOUD_DECL_EXPORT __attribute__((visibility("default")))
#endif
```
而后，符号可见
<img width="467" alt="屏幕快照 2019-07-13 18 42 52" src="https://user-images.githubusercontent.com/6168604/61170624-6b973c00-a59e-11e9-90ab-15dcceedd4ff.png">

```
if(CMAKE_HOST_UNIX) 确定在mac下这里不会跑偏到“LINUX”？？？
		set(PLATFORM_LINUX 1)
		set(TARGET_OS "LINUX")
	elseif(CMAKE_HOST_WIN32)
		set(PLATFORM_WINDOWS 1)
		set(TARGET_OS "WINDOWS")
	elseif(CMAKE_HOST_APPLE)
		set(PLATFORM_APPLE 1)
		set(TARGET_OS "APPLE")
	else()
		message(FATAL_ERROR "Do not support unknown host OS")
	endif()
```

**Comment by huiguangjun** [comment]
已经修改，如何到 mater分支。
