### ISSUE TITLE
是否可以在生产环境使用？

### ISSUE THREAD

**Issue by halk947** [aliyun/aliyun-oss-cpp-sdk#3]
现在我们使用的是[aliyun-oss-c-sdk](https://github.com/aliyun/aliyun-oss-c-sdk)
这个repo是oss sdk的cpp版本，但并没有在阿里云`SDK 文档简介`中看到相关说明，希望确认两个问题：
1. 功能是否完善
2. 是否可以在线上进行使用

谢谢

**Comment by huiguangjun** [comment]
文档部分已经在同步更新，这个月上线到官网。
就你提到的几点：
1）功能是完善的，涵盖了 c sdk 3.6.0 版本 的所有功能，同时也新增一些新特性，例如异步接口，上传下载限速，基于client 的 上传打断，重试，时间自动校正等 
2）该sdk是经过测试的，代码覆盖率在 93+%，对上传，下载接口也做了长时间的压力测试。
3）该sdk在 vs2013及以上, gcc4.8及以上， clang3.3 及以上 编译器 和 多个平台上测试。
4）未来有多平台运行的需求，建议往这个sdk迁移，它对第三方库的依赖也比较少(只依赖libcurl和openss)， 移植性比好。
5）当然，这个是新版本的SDK，在你们的生产环境上使用时，还是需要经过你们自己的测试和验证。
