### ISSUE TITLE
能不能指定网卡？

### ISSUE THREAD

**Issue by keguo1119** [aliyun/aliyun-oss-cpp-sdk#5]
socket 编程可以指定网卡，我有eth0, eth1 两个网卡，想要指定eth1, 此sdk 上层函数有没有指定网口的功能

**Comment by huiguangjun** [comment]
sdk 封装了 libcurl 作为其 http的请求实现。 
libcurl 提供了API 可以 指定interface。 后续版本会把这个接口开放出来。

你可以参考  ClientConfiguration.caPath 的 方式 在现在的版本上自行添加。  对应到的libcurl 的接口 为 
curl_easy_setopt(curl, CURLOPT_INTERFACE, "eth0");
具体 详见 https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html

**Comment by huiguangjun** [comment]
该功能已经提交到 dev-1903分支上。 
可以通过 ClientConfiguration.networkInterface  设置。

**Comment by keguo1119** [comment]
还想问下，我当前用的是 C 的SDK, C 这个选项是不是没有开启

**Comment by huiguangjun** [comment]
c sdk 没有提供这个选项。
