### ISSUE TITLE
上传直接从内存创建的二进制文件出错

### ISSUE THREAD

**Issue by tooyamk** [aliyun/aliyun-oss-cpp-sdk#51]
class membuf : public std::streambuf {
public:
	membuf(char* p, size_t n) {
		setg(p, p, p + n);
	}
};

auto buf = new membuf(new char[n], n);
auto content = std::make_shared<std::iostream>(buf);
AlibabaCloud::OSS::PutObjectRequest request(BucketName, Key, content);
client.PutObject(request);

返回的信息是code:ParseXMLError，msg:XML_ERROR_MISMATCHED_ELEMENT

我尝试直接用stringstream上传字符串是正常的，但是不知道这个二进制上传哪里出的问题

**Comment by huiguangjun** [comment]
你可以参考一下  https://github.com/aliyun/aliyun-oss-cpp-sdk/issues/12

**Comment by elesos** [comment]
std::shared_ptr<std::iostream> content = std::make_shared<std::fstream>("D:\\test_files\\c6252446d568221ed2a78db44988d9c1.txt", std::ios::in | std::ios::binary);

报：PutObject fail:code:[ParseXMLError:16],message:[XML_ERROR_MISMATCHED_ELEMENT],requestId:
中括号里面是outcome.error().Code() 和outcome.error().Message()的输出。
请问是什么原因？
