### ISSUE TITLE
sdk静态库，使用时链接错误，求帮忙。。。

### ISSUE THREAD

**Issue by bigggggdady** [aliyun/aliyun-oss-cpp-sdk#52]
alibabacloud-oss-cpp-sdk.lib(Utils.obj) : error LNK2019: 无法解析的外部符号 EVP_MD_CTX_init，该符号在函数 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl AlibabaCloud::OSS::ComputeContentMD5(class std::basic_istream<char,struct std::char_traits<char> > &)" (?ComputeContentMD5@OSS@AlibabaCloud@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$basic_istream@DU?$char_traits@D@std@@@4@@Z) 中被引用

alibabacloud-oss-cpp-sdk.lib(CurlHttpClient.obj) : error LNK2019: 无法解析的外部符号 __imp_curl_global_init，该符号在函数 "public: static void __cdecl AlibabaCloud::OSS::CurlHttpClient::initGlobalState(void)" (?initGlobalState@CurlHttpClient@OSS@AlibabaCloud@@SAXXZ) 中被引用

**Comment by bigggggdady** [comment]
发现了一个已关闭的同样的问题

**Comment by silverbers** [comment]
大佬解决了吗?

**Comment by silverbers** [comment]
我用OpenSSL 1.1.1n的头文件替换了他的后, 出现了EVP_MD_CTX_new  EVP_MD_CTX_reset  EVP_MD_CTX_free  三个未找到的函数符号 , 但是我看头文件中是有宏定义重定向函数名到新版本的 , 不知道为什么不生效
