### ISSUE TITLE
带有中文名字的文件传不上去

### ISSUE THREAD

**Issue by Greedysky** [aliyun/aliyun-oss-cpp-sdk#59]
RT 带有中文名字的文件传不上去，显示参数非法

**Comment by Greedysky** [comment]
添加Content-Type 为utf-8解决

**Comment by uknowsec** [comment]
> 添加Content-Type 为utf-8解决
PutObject fail,code:InvalidArgument,message:The characters encoding must be utf-8.
可以问一下具体解决方案么？
