### ISSUE TITLE
将OpenSSL更换成静态库，提示未找到LIBEAY.DLL

### ISSUE THREAD

**Issue by dataonfirecn** [aliyun/aliyun-oss-cpp-sdk#65]
因为要做一个插件，希望把openssl转成静态库，避免手动导入Dll文件。
编译过程是没问题的，分别编译出libeay32.lib（13MB）和ssleay32.lib（2MB），单独测试也是成功的。OpenSSL的版本是1.0.2p。
但是替换了lib为静态库后，我在程序目录删除libeay32.dll和sslyea32.dll，运行时提示未找到LIBEAY.DLL。
请教是否oss的sdk本身不支持这样使用openssl静态库的操作。
谢谢

**Comment by huiguangjun** [comment]
这个和你链接时，选择的依赖库有关系，你可以到你生成 dll（exe） 的工程里，看一下 linker->input->additional dependencies 下看一下依赖的库是什么？ 是不是你修改过的那些静态库文件，如果不是，手动修改一下。

**Comment by 2222ex** [comment]
![Image](https://github.com/user-attachments/assets/bb2efc5d-4cce-4963-8e23-545f8ca6ff13) 实际上还有一个libcurl.dll使用到了openssl的动态链接库
