### ISSUE TITLE
OSS_CPP有crc校验吗？

### ISSUE THREAD

**Issue by queention** [aliyun/aliyun-oss-cpp-sdk#7]

**Comment by queention** [comment]
我现在通过curl下载的图片，进行展示，但是有时候图片并没有下载完全，所以图片展示不出来，有没有OSS_CPP进行校验的一个方法呢？

**Comment by huiguangjun** [comment]
cpp sdk 上传 和下载 默认是打开 crc64 校验的。

**Comment by xupeidong** [comment]
咱们下载的SDK接口或者demo在哪呢？我没有找见
