### ISSUE TITLE
上传文件成功,但是提示错误

### ISSUE THREAD

**Issue by XieShaosong** [aliyun/aliyun-oss-cpp-sdk#70]
"PutObject fail, code ClientError:200052, message Server returned nothing (no headers, no data), requestId:"

**Comment by huiguangjun** [comment]
std::shared_ptr<HttpResponse> CurlHttpClient::makeRequest(const std::shared_ptr<HttpRequest> &request)
    {
         OSS_LOG(LogLevel::LogDebug, TAG, "request(%p) enter makeRequest", request.get());
         curl_slist *list = nullptr;
         auto& headers = request->Headers();
         for (const auto &p : headers) {
             if (p.second.empty())
                 continue;
             std::string str = p.first;
             str.append(": ").append(p.second);
             list = curl_slist_append(list, str.c_str());
         }
         // 你可以修改一下代码，增加下面这段代码
         list = curl_slist_append(list, "Expect:");

**Comment by huiguangjun** [comment]
已经更新到 1.8.1 版本
