### ISSUE TITLE
 AlibabaCloud::OSS::Outcome error LNK2019

### ISSUE THREAD

**Issue by wongdu** [aliyun/aliyun-oss-cpp-sdk#77]
报错" error LNK2019: 无法解析的外部符号 "public: class AlibabaCloud::OSS::Outcome<class AlibabaCloud::OSS::OssError,class AlibabaCloud::OSS::GetObjectResult> __cdecl AlibabaCloud::OSS::OssClient::GetObjectW(class AlibabaCloud::OSS::GetObjectRequest const &)const " (?GetObjectW@OssClient@OSS@AlibabaCloud@@QEBA?AV?$Outcome@VOssError@OSS@AlibabaCloud@@VGetObjectResult@23@@23@AEBVGetObjectRequest@23@@Z)，该符号在函数 "int __cdecl AliYunOssDownLoadFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?AliYunOssDownLoadFile@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV12@@Z) 中被引用"，请问怎么解决

**Comment by keacefull** [comment]
哥们，怎么解决的？我一直没有解决

**Comment by Degfy** [comment]
参考：https://blog.csdn.net/yangchuangbao/article/details/80829966
